//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRemocon_Manager_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationCode
    {
        public int ID { get; set; }
        public int iRemocon_id { get; set; }
        public int RegistrationCode1 { get; set; }
        public string Detail { get; set; }
    
        public virtual iRemocon iRemocon { get; set; }
    }
}
